name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@master
       with:
         fetch-depth: 2
     - name: run docker container
       uses: docker://yangyw12345/tex-builder
       with:
         args: make all
